### ISSUE TITLE
Bug: Large download fails

### ISSUE THREAD

**Issue by dewarim** [dewarim/cinnamon#129]
User reported that downloading an object of 1 GByte size failed on his machine.

**Comment by dewarim** [comment]
`java.lang.IllegalStateException: getOutputStream() has already been called on this response.

        at cinnamon.servlet.HttpServletResponseCopier.getWriter(HttpServletResponseCopier.java:40)

        at org.grails.plugins.web.rest.api.ControllersRestApi.render(ControllersRestApi.groovy:53)

        at cinnamon.BaseController.renderErrorXml(BaseController.groovy:58)

        at cinnamon.BaseController.renderExceptionXml(BaseController.groovy:77)

       at cinnamon.CinnamonController.legacy(CinnamonController.groovy:278)

        at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)

        at grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter.doFilter(RequestHolderAuthenticationFilter.java:53)

        at cinnamon.RequestTicketAuthenticationFilter.doFilter(RequestTicketAuthenticationFilter.groovy:102)

        at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:62)

        at cinnamon.servlet.ResponseFilter.doFilter(ResponseFilter.java:43)

        at com.brandseye.cors.CorsFilter.doFilter(CorsFilter.java:82)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

        at java.lang.Thread.run(Thread.java:745)

2016-09-29 16:43:57,419 http-nio-8080-exec-6 org.codehaus.groovy.grails.web.servlet.GrailsDispatcherServlet Recursive rendering of error view detected.

org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: getOutputStream() has already been called on this response.

        at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)

        at grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter.doFilter(RequestHolderAuthenticationFilter.java:53)

        at cinnamon.RequestTicketAuthenticationFilter.doFilter(RequestTicketAuthenticationFilter.groovy:102)

        at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:62)

        at cinnamon.servlet.ResponseFilter.doFilter(ResponseFilter.java:43)

        at com.brandseye.cors.CorsFilter.doFilter(CorsFilter.java:82)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

        at java.lang.Thread.run(Thread.java:745)

Caused by: java.lang.IllegalStateException: getOutputStream() has already been called on this response.

        at cinnamon.servlet.HttpServletResponseCopier.getWriter(HttpServletResponseCopier.java:40)

        at java.io.FilterWriter.flush(FilterWriter.java:100)

        ... 9 more`
