### ISSUE TITLE
Missing javaScript provider

### ISSUE THREAD

**Issue by dewarim** [dewarim/cinnamon#71]
SCHWERWIEGEND: Servlet.service() for servlet [default] in context with path [/cinnamon] threw exception [Request processing failed; nested exception is org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error applying layout : main] with root cause
org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: No javascript provider is configured
        at gsp_cinnamon_layoutsmain_gsp$_run_closure2.doCall(gsp_cinnamon_layoutsmain_gsp.groovy:95)
        at gsp_cinnamon_layoutsmain_gsp.run(gsp_cinnamon_layoutsmain_gsp.groovy:122)
        at grails.plugin.springsecurity.web.access.AjaxAwareAccessDeniedHandler.handle(AjaxAwareAccessDeniedHandler.java:77)
        at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)
        at grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter.doFilter(RequestHolderAuthenticationFilter.java:49)
        at humulus.RepositoryLoginFilter.doFilter(RepositoryLoginFilter.groovy:123)
        at cinnamon.RequestTicketAuthenticationFilter.doFilter(RequestTicketAuthenticationFilter.groovy:113)
        at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:82)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by dewarim** [comment]
Fixed by 0a4148572e
